name: Tensorflow model
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - name: Environment setup # Set up with a specific version of Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Cache # Cache dependencies
        uses: actions/cache@v2

      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
